/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.HeadlessException;

/**
 *
 * @author RIZKI - SYSDEV
 */
public class FormSPP extends javax.swing.JFrame {

    /**
     * Creates new form FormSPP
     */
    public FormSPP() {
        initComponents();
        GetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idSiswa = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jurusan = new javax.swing.JComboBox<>();
        namaSiswa = new javax.swing.JTextField();
        pembayaran = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembayaran = new javax.swing.JTable();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEM PEMBAYARAN SPP SMP JAKENAN");

        jLabel2.setLabelFor(jLabel2);
        jLabel2.setText("Pembayaran");

        jLabel3.setLabelFor(jLabel2);
        jLabel3.setText("ID Siswa : ");

        idSiswa.setName("idSiswa"); // NOI18N
        idSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSiswaActionPerformed(evt);
            }
        });

        kelas.setName("kelas"); // NOI18N
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Siswa");

        jLabel5.setText("Jumlah");

        jLabel6.setLabelFor(jLabel2);
        jLabel6.setText("Kelas :");

        jLabel7.setText("Jurusan");

        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Rekayasa Perangkat Lunak", "Akuntansi", "Multimedia", "Teknik Komputer Jaringan", "Administrasi Perkantoran" }));
        jurusan.setToolTipText("Pilih");
        jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanActionPerformed(evt);
            }
        });

        pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Tunai", "Transfer Bank" }));

        tabelPembayaran.setAutoCreateRowSorter(true);
        tabelPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Siswa", "Nama Siswa", "Kelas", "Jurusan", "Jumlah", "Pembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelPembayaran);
        if (tabelPembayaran.getColumnModel().getColumnCount() > 0) {
            tabelPembayaran.getColumnModel().getColumn(0).setPreferredWidth(32);
            tabelPembayaran.getColumnModel().getColumn(2).setPreferredWidth(32);
            tabelPembayaran.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        simpanBtn.setText("Simpan Pembayaran");
        simpanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanBtnMouseClicked(evt);
            }
        });
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Pembayaran");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Hapus Pembayaran");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Cetak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kelas)
                    .addComponent(idSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaSiswa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jurusan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(simpanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(deleteBtn)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(info)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void GetData(){
        DefaultTableModel model = (DefaultTableModel) tabelPembayaran.getModel();
        model.setRowCount(0);
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM spp";
            ResultSet result = statement.executeQuery(sql);
            // load data to jtable
            while (result.next()){
                Object[] object = new Object[6];
                object[0]=result.getString("idSiswa");
                object[1]=result.getString("namaSiswa");
                object[2]=result.getString("kelas");
                object[3]=result.getString("jurusan");
                object[4]=result.getString("pembayaran");
                object[5]=result.getString("jumlah");
                model.insertRow(0, object);
            }
            result.close();
            statement.close();
        }
        catch (SQLException | HeadlessException e){
            
        }
    }
    private void idSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSiswaActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed
    private void clearForm(){
        this.idSiswa.setText("");
        this.namaSiswa.setText("");
        this.kelas.setText("");
        this.jurusan.setSelectedItem("Pilih");
        this.pembayaran.setSelectedItem("Pilih");
        this.jumlah.setText("");
    }
    private void simpanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabelPembayaran.getModel();        
        // ambil nilai inputan:
        String idSiswa = this.idSiswa.getText();
        String namaSiswa = this.namaSiswa.getText();
        String kelas = this.kelas.getText();
        String jurusan = this.jurusan.getSelectedItem().toString();
        String pembayaran = this.pembayaran.getSelectedItem().toString();
        Integer jumlah = Integer.parseInt(this.jumlah.getText()) ;
        // insert data to table sql
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
            Statement insertStatement = connection.createStatement();
            String sql = "INSERT INTO `spp` (`idSiswa`, `namaSiswa`, `kelas`, `jurusan`, `pembayaran`, `jumlah`) VALUES ('"+idSiswa+"','"+namaSiswa+"','"+kelas+"','"+jurusan + "','"+pembayaran+"','"+jumlah+"');";
            insertStatement.executeUpdate(sql);
            GetData();
            JOptionPane.showMessageDialog(null, "Transaksi Berhasil Disimpan / Diupdate");
            clearForm();
        }
        catch (SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "Gagal Update / Tambah Pembayaran.");
            clearForm();
            System.err.println(e);
        }
        
        
    }//GEN-LAST:event_simpanBtnMouseClicked

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here:
        if(tabelPembayaran.getSelectedRow() != -1){
            DefaultTableModel model = (DefaultTableModel) tabelPembayaran.getModel();
            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
                Statement statement = connection.createStatement();
                String idSiswa = model.getValueAt(tabelPembayaran.getSelectedRow(), 0).toString();
                String sql = "SELECT * FROM `spp` WHERE idSiswa = "+idSiswa;
                ResultSet result = statement.executeQuery(sql);
                // get data value and update to input
                String namaSiswa = ""; 
                String kelas = "";
                String jurusan = "";
                String jumlah = "";
                String pembayaran = ""; 
                while (result.next()){
                    namaSiswa=result.getString("namaSiswa");
                    kelas=result.getString("kelas");
                    jurusan=result.getString("jurusan");
                    pembayaran=result.getString("pembayaran");
                    jumlah=result.getString("jumlah");
                }
                // update input
                this.idSiswa.setText(idSiswa);
                this.namaSiswa.setText(namaSiswa);
                this.kelas.setText(kelas);
                this.jumlah.setText(jumlah);
                this.jurusan.setSelectedItem(jurusan);
                this.pembayaran.setSelectedItem(pembayaran);
                result.close();
                statement.close();
                // hapus data dari existing tabel         
                String deleteSql = "DELETE FROM `spp` WHERE idSiswa = "+idSiswa;
                Statement deleteStatement = connection.createStatement();
                deleteStatement.executeUpdate(deleteSql);
                GetData();
            } catch (SQLException | HeadlessException e){
                 JOptionPane.showMessageDialog(null, "Gagal Update / Tambah Pembayaran.");
            }
            //remove old data
            model.removeRow(tabelPembayaran.getSelectedRow());
        }
    }//GEN-LAST:event_updateBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        if(tabelPembayaran.getSelectedRow() != -1){
            DefaultTableModel model = (DefaultTableModel) tabelPembayaran.getModel();
            String idSiswa = model.getValueAt(tabelPembayaran.getSelectedRow(), 0).toString();
            // execute query sql
            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
                Statement insertStatement = connection.createStatement();
                String sql = "DELETE FROM `spp` WHERE idSiswa = "+idSiswa;
                insertStatement.executeUpdate(sql);
                GetData();
                JOptionPane.showMessageDialog(null, "Pembayaran berhasil dihapus / dibatalkan");
            } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Gagal menghapus data Pembayaran.");
                clearForm();
                System.err.println(e);
            }
            
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField idSiswa;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField namaSiswa;
    private javax.swing.JComboBox<String> pembayaran;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTable tabelPembayaran;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
